import React, { useEffect, useState } from 'react';
import { ArrowLeft, Sparkles, TrendingUp, Users, Target, Lightbulb, DollarSign } from 'lucide-react';
import { BusinessIdea } from '../types';
import { shareUtils } from '../utils/shareUtils';

interface SharedIdeaPageProps {
  onNavigateToLanding: (suggestedInput?: string) => void;
}

export const SharedIdeaPage: React.FC<SharedIdeaPageProps> = ({ onNavigateToLanding }) => {
  const [sharedIdea, setSharedIdea] = useState<BusinessIdea | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const idea = shareUtils.parseSharedUrl();
    if (idea) {
      setSharedIdea(idea);
    } else {
      setError('Invalid or expired share link');
    }
    setLoading(false);
  }, []);

  const getScoreColor = (score: number) => {
    if (score >= 8) return 'text-green-600 bg-green-100';
    if (score >= 6) return 'text-yellow-600 bg-yellow-100';
    return 'text-red-600 bg-red-100';
  };

  const getGrowthColor = (growth: number) => {
    if (growth >= 20) return 'text-green-600 bg-green-100';
    if (growth >= 10) return 'text-blue-600 bg-blue-100';
    return 'text-gray-600 bg-gray-100';
  };

  const MetricBar = ({ value, max = 10, color = 'bg-blue-500' }: { value: number; max?: number; color?: string }) => (
    <div className="w-full bg-gray-200 rounded-full h-2">
      <div 
        className={`h-2 rounded-full ${color}`} 
        style={{ width: `${(value / max) * 100}%` }}
      />
    </div>
  );

  const handleGenerateSimilar = () => {
    // Navigate to main app with the shared idea's context
    onNavigateToLanding(`Generate ideas similar to: ${sharedIdea?.title}`);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading shared idea...</p>
        </div>
      </div>
    );
  }

  if (error || !sharedIdea) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <div className="text-center max-w-md">
          <div className="text-6xl mb-4">🔗</div>
          <h1 className="text-2xl font-bold text-gray-800 mb-2">Invalid Share Link</h1>
          <p className="text-gray-600 mb-6">
            This share link is invalid or has expired. Please check the URL or ask for a new share link.
          </p>
          <button
            onClick={() => onNavigateToLanding()}
            className="bg-blue-600 text-white px-6 py-3 rounded-lg hover:bg-blue-700 transition-colors"
          >
            Go to AI Factory
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white shadow-sm">
        <div className="max-w-4xl mx-auto px-4 py-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <button
                onClick={() => onNavigateToLanding()}
                className="flex items-center gap-2 text-gray-600 hover:text-gray-800 transition-colors"
              >
                <ArrowLeft className="w-5 h-5" />
                <span>Back to AI Factory</span>
              </button>
            </div>
            <div className="text-sm text-gray-500">
              💡 Shared Business Idea
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-gray-800 mb-2">
            Someone shared a business idea with you!
          </h1>
          <p className="text-gray-600">
            Generated by AI Factory - Your AI-powered business idea generator
          </p>
        </div>

        {/* Shared Idea Card */}
        <div className="bg-white rounded-2xl p-8 shadow-sm border border-gray-100 mb-8">
          {/* Header with Overall Score and Growth */}
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-3">
              <div className={`px-4 py-2 rounded-lg text-lg font-bold ${getScoreColor(sharedIdea.score)}`}>
                {sharedIdea.score}/10
              </div>
              <div className={`px-3 py-1 rounded-lg text-sm font-medium ${getGrowthColor(sharedIdea.growthPercentage)}`}>
                <TrendingUp className="w-4 h-4 inline mr-1" />
                {sharedIdea.growthPercentage}% Growth
              </div>
            </div>
            <div className="text-sm text-gray-500">
              Shared via AI Factory
            </div>
          </div>

          {/* Title and Description */}
          <div className="mb-6">
            <h2 className="text-2xl font-bold text-gray-800 mb-3 leading-tight">
              {sharedIdea.title}
            </h2>
            <p className="text-gray-600 leading-relaxed text-lg">
              {sharedIdea.description}
            </p>
          </div>

          {/* Detailed Metrics */}
          <div className="mb-6">
            <h3 className="text-lg font-semibold text-gray-800 mb-4">Business Metrics</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2" title="Size of the target market and potential customer base">
                    <Users className="w-4 h-4 text-blue-500" />
                    <span className="text-gray-700 font-medium">Market Size</span>
                  </div>
                  <span className="font-bold text-lg">{sharedIdea.metrics.marketSize}/10</span>
                </div>
                <MetricBar value={sharedIdea.metrics.marketSize} color="bg-blue-500" />
              </div>
              
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2" title="Level of competition in the market (10 = blue ocean, 1 = saturated)">
                    <Target className="w-4 h-4 text-purple-500" />
                    <span className="text-gray-700 font-medium">Competition</span>
                  </div>
                  <span className="font-bold text-lg">{sharedIdea.metrics.competition}/10</span>
                </div>
                <MetricBar value={sharedIdea.metrics.competition} color="bg-purple-500" />
              </div>
              
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2" title="How realistic and achievable this business idea is">
                    <Lightbulb className="w-4 h-4 text-yellow-500" />
                    <span className="text-gray-700 font-medium">Feasibility</span>
                  </div>
                  <span className="font-bold text-lg">{sharedIdea.metrics.feasibility}/10</span>
                </div>
                <MetricBar value={sharedIdea.metrics.feasibility} color="bg-yellow-500" />
              </div>
              
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2" title="Potential for generating profit and sustainable revenue">
                    <DollarSign className="w-4 h-4 text-green-500" />
                    <span className="text-gray-700 font-medium">Profitability</span>
                  </div>
                  <span className="font-bold text-lg">{sharedIdea.metrics.profitability}/10</span>
                </div>
                <MetricBar value={sharedIdea.metrics.profitability} color="bg-green-500" />
              </div>
            </div>
          </div>
        </div>

        {/* Call to Action */}
        <div className="bg-gradient-to-r from-blue-50 to-purple-50 rounded-2xl p-8 text-center">
          <div className="mb-6">
            <Sparkles className="w-12 h-12 text-blue-600 mx-auto mb-4" />
            <h2 className="text-2xl font-bold text-gray-800 mb-2">
              Want ideas like this?
            </h2>
            <p className="text-gray-600 text-lg">
              Generate unlimited business ideas tailored to your interests with AI Factory
            </p>
          </div>

          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button
              onClick={handleGenerateSimilar}
              className="bg-blue-600 text-white px-8 py-3 rounded-lg hover:bg-blue-700 transition-colors font-medium text-lg flex items-center justify-center gap-2"
            >
              <Sparkles className="w-5 h-5" />
              Generate Similar Ideas
            </button>
            <button
              onClick={() => onNavigateToLanding()}
              className="bg-white text-gray-700 px-8 py-3 rounded-lg hover:bg-gray-50 transition-colors font-medium text-lg border border-gray-200"
            >
              Explore AI Factory
            </button>
          </div>
        </div>

        {/* Footer */}
        <div className="text-center mt-12 pt-8 border-t border-gray-200">
          <p className="text-gray-500">
            Powered by <span className="font-semibold text-blue-600">AI Factory</span> - 
            Your AI-powered business idea generator
          </p>
        </div>
      </div>
    </div>
  );
};
